from . import life_style_masters
#from . import brand_master
from . import cashier_master
#from . import category_master
from . import company_master
#from . import customer_master
#from . import department_master
#from . import item_type_master
#from . import locator_master
#from . import product_color_master
#from . import Product_design_master
#from . import product_master
#from . import product_size_master
#from . import purchase_vat_master
#from . import sub_category_master
from . import vendor_master
from . import organization_master
from . import schedule_action
from . import res_company

